### ISSUE TITLE
Setup CNAME Redirect for jupinx.quantecon.org

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#13]
Target address = https://quantecon.github.io/jupinx/

**Comment by mmcky** [comment]
@DrDrij let's only do this once the project is ready for public.

**Comment by DrDrij** [comment]
I've tested this on a repository in my personal account and had no problems setting this up. We will be able to use a jupinx subdomain:

`quantecon.github.io/jupinx/` -> `jupinx.quantecon.org`

**Comment by mmcky** [comment]
@DrDrij do you mind going ahead and setting this up? Please close this issue once done. Thanks!

**Comment by DrDrij** [comment]
@mmcky Sure thing. Do you mind giving me permissions on the repository to edit settings? Missing this option on the repo.

![image](https://user-images.githubusercontent.com/5886045/62381384-078be600-b554-11e9-8525-4283a8021da1.png)

**Comment by DrDrij** [comment]
@mmcky This is ready :) 
https://jupinx.quantecon.org/
