### ISSUE TITLE
Update project site to be driven by markdown

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#16]
It would be easier to edit if the page site was available in markdown documents.

@DrDrij can you please investigate:
https://github.blog/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/

It looks like Github pages uses Jekyll in the background.

**Comment by DrDrij** [comment]
@mmcky I've converted the HTML site to a very simple Jekyll theme and swapped out the `index.html` with an `index.md`.

https://github.com/QuantEcon/jupinx/blob/master/docs/index.md

This updated and published immediately: https://quantecon.github.io/jupinx/

**Comment by jstac** [comment]
Thanks @DrDrij !

That's great `:-)`
