### ISSUE TITLE
FEAT: Add jupinx --preview to open notebook server

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#21]
We should support `preview` option to open a notebook server in `_build/jupyter`

**Comment by jstac** [comment]
+1

`jupinx --preview` and `jupinx -p`?

And for the website after `jupyter -w`?  `jupinx --preview --website` and `jupinx -pw`?

**Comment by mmcky** [comment]
@jstac we are working on enforcing an order to provided arguments to implement the chain of events. If `jupinx --preview --website` is issued then it would request a `make website` followed by a `make preview` once completed.

**Comment by jstac** [comment]
OK, so how about `jupinx --preview-website` and `jupinx -pw`?

**Comment by mmcky** [comment]
The issue with `-p` and `--preview` is that we currently have allocated `-p` and `--parallel`. 

Would `-v, --view` be suitable alternatives or should we use `-j` for parallel?

**Comment by jstac** [comment]
Ah `:-)`.

Let's go for `-v` and `--view`

**Comment by mmcky** [comment]
this has been implemented in pr #29
