### ISSUE TITLE
FEAT: Add -c, --clean to force a clean run

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#26]
It would be nice to have `-c, --clean` to force a clean run through `jupinx`

**Comment by mmcky** [comment]
given `-c` is current short for `--coverage` will need to think about names here.

**Comment by jstac** [comment]
how about `-t` is short for `--coverage-tests`?

**Comment by mmcky** [comment]
great idea @jstac -- I think that is a good solution.
