### ISSUE TITLE
Check: sphinx=2.1.2 tornado warning from jupyter_kernels

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#33]

**Comment by AakashGfude** [comment]
tornado error does not seem to be coming in my system. We have to check the system configuration of  @jstac to reproduce it.

**Comment by jstac** [comment]
Let me know how I can help.

**Comment by mmcky** [comment]
hey @jstac would you be able to run: `conda env export > environment.yml` and send through the environment.yml file. We should be able to replicate your conda environment exactly that way.
