### ISSUE TITLE
BUG: Minimal `html` template to support make website

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/jupinx#50]
@DrDrij we would like to add templates to support `html` conversion using `nbconvert` but it should be a simple minimal example for `jupinx-quickstart`. It would be great if you could put one together and we will remove the `lectures-nbconvert.tpl`: 

https://github.com/QuantEcon/jupinx/tree/master/jupinx/templates/html

The minimal template for html should include:

1. simple looking layout
1. lots of documentation in the template file for users to make adjustments
1. minimal css file (if required). 

- [x] update `jupinx-quickstart` and add question if user wants to build websites from `sphinxcontrib-jupyter` to populate with `make website` and `templates`
- [x] populate `theme/templates` with html template and add necessary options to `conf.py` file.

**Comment by DrDrij** [comment]
On my radar.

**Comment by mmcky** [comment]
thanks @DrDrij

**Comment by mmcky** [comment]
hey @DrDrij just fyi this theme will be used as the default theme for editing on `lecture-source-py` and only the `qe-lectures` theme will be deployed on the `build` server. That way we can remove from `lecturre-source-py`

**Comment by DrDrij** [comment]
Got it @mmcky. On my radar.

**Comment by mmcky** [comment]
thanks @DrDrij closing now.
