### ISSUE TITLE
Bug -- Please see image (problem with path)

### ISSUE THREAD

**Issue by jstac** [QuantEcon/jupinx#54]
![Screenshot_2019-08-07_04-52-39](https://user-images.githubusercontent.com/3887684/62567675-04d01e80-b8cf-11e9-802c-ab7cdd1fa6d7.png)

**Comment by mmcky** [comment]
thanks @jstac. Do you know if you typed the `python_lectures_sandpit` in full and not used path completion from shell. 

@AakashGfude we should check if `/` is in place for the directory path (when specified) -- and if it isn't we should add it to always ensure complete paths.
