### ISSUE TITLE
quickstart deselection of kernels embedding json in python

### ISSUE THREAD

**Issue by GavinHuttley** [QuantEcon/jupinx#78]
`jupinx-quickstart` gives the option of including/not julia 1.1 etc. I selected `n`. Then  running `jupinx -w` fails with:
```
 $ jupinx -w
Running: make website
Running Sphinx v2.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/gavin/miniconda3/envs/jupinx/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/gavin/miniconda3/envs/jupinx/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/gavin/Desktop/Inbox/jupinx-project/conf.py", line 73, in <module>
    "julia-1.1": false,
NameError: name 'false' is not defined

make: *** [website] Error 2
```
Checking `conf.py` reveals the following `json` statements:
```python
    "julia-1.1": false,
    "julia-1.2": false,
    "python2": false,
```
Changing the `false` to `False` allows successful generation of the website.

**Comment by mmcky** [comment]
Thanks @GavinHuttley will submit a fix for that. That looks like incorrect `python` syntax being applied from the `template` used to generated the repository. 

We would like to include autodetection of installed kernels to replace these questions. 

@AakashGfude next week can we setup `CI` and do some more rigourous testing of the quickstart.

**Comment by mmcky** [comment]
thanks @GavinHuttley closing this as a fix has now been merged.

**Comment by mtiley** [comment]
@mmcky I'm still having this problem as of jupinx 0.2.2: 

<img width="610" alt="jupinx-error" src="https://user-images.githubusercontent.com/56301568/75513765-e3d94180-5a49-11ea-94c5-765ce4156665.PNG">

Do you want me to make a new issue?

**Comment by mmcky** [comment]
thanks @mtiley you need to update `false` to `False` in `conf.py` or delete the `julia` setting all together. It is an issue with our quickstart in `v0.2.2`.

**Comment by mtiley** [comment]
Thanks @mmcky
