### ISSUE TITLE
quickstart false bug

### ISSUE THREAD

**Issue by jstac** [QuantEcon/jupinx#83]
After running `jupinx-quickstart` and replying `n` to Julia, the conf.py file contains the lines

```
"julia-1.1": false,
"julia-1.2": false,
```

Here `false` should be replaced by `False`.

**Comment by mmcky** [comment]
thanks for reporting this @jstac this has been fixed in https://github.com/QuantEcon/jupinx/pull/79 but not yet included in the latest release. This will be included in this weeks release through PyPI.

**Comment by juanbono** [comment]
@mmcky  How can install the version you mention above? I installed it via `pip install jupinx` and it downloaded jupinx 0.2.2 (which has the quickstart bug)
