### ISSUE TITLE
update ``pip`` to ``pip3``

### ISSUE THREAD

**Issue by shlff** [QuantEcon/jupinx#95]
Hi @jstac and @mmcky , I find we still use ``pip install --upgrade python`` in the [tutorial](https://jupinx.quantecon.org/tutorial) of ``Jupinx``. Since Python 2.7 reached its end of life on January 1st, 2020, this command line would cause some warnings, like the one attached below. 

Shall we update it by using ``pip3``? I am afraid that this command line would cause warnings elsewhere, such as our lectures.

<img width="705" alt="Screen Shot 2020-03-30 at 4 34 43 pm" src="https://user-images.githubusercontent.com/53931041/77878599-61d87480-72a4-11ea-9bdf-0ef0d9d1a0b7.png">

**Comment by mmcky** [comment]
hey @shlff I am surprised that the `pip` your machine is using is the `system-wide` pip. do you have `anaconda` installed and is it in your `.bashrc` (pre os x 10.15) or `zsh` profile `(post os x 10.15). If `anaconda` is setup i think `pip` should use the correct pip (i.e. pip3)

**Comment by shlff** [comment]
Thanks for your advice, @mmcky . I figured out what happened here and solved this issue. This occurred because if I had or installed ``Python`` before, even though my ``anaconda`` is set up, ``pip`` would not use the python installed under ``anaconda``. I need to modify the path in my ``zsh`` profile.

Now, I set Python3 globally as my default python version and update ``pip`` to ``pip3`` on my mac by using [pyenv](https://github.com/pyenv/pyenv).

Do you think we should add a note here?

**Comment by shlff** [comment]
Thanks @mmcky . I understand what happens here. I will close this issue.
